pipeline {
   agent {
     node {
      label 'TestNode' 
   }
}
stages {
    
    stage('Checkout') {
    steps {
    	echo 'step Git Checkout'
		checkout scm
        }
    }
    stage('Build') {
        steps {
        sh 'chmod +x ./mvnw'
        sh './mvnw clean install' 
        }
    }
    stage('FindBug') {
        steps{
            recordIssues aggregatingResults: true, tools: [findBugs(useRankAsPriority: true)]
        }
    }
    stage('DependencyCheck') {
        steps{
            recordIssues(tools: [owaspDependencyCheck()])
        }
    }

}
}
