pipeline {
   agent {
     node {
      label 'TestNode' 
   }
}
stages {
    
    stage('Checkout') {
    steps {
    	echo 'step Git Checkout'
		checkout scm
        }
    }
    stage('Build') {
        steps {
        sh 'chmod +x ./mvnw'
        sh './mvnw clean install' 
        }
    }
  
    stage('FindBug') {
        steps{
            recordIssues aggregatingResults: true, tools: [findBugs(useRankAsPriority: true)]
        }
    }
            stage ('Analysis') {
            steps {
                sh '${M2_HOME}/bin/mvn --batch-mode -V -U -e checkstyle:checkstyle pmd:pmd pmd:cpd findbugs:findbugs spotbugs:spotbugs'
            }
        }
    }
    post {
        always {
            junit testResults: '**/target/surefire-reports/TEST-*.xml'

            recordIssues enabledForFailure: true, tools: [mavenConsole(), java(), javaDoc()]
            recordIssues enabledForFailure: true, tool: checkStyle()
            recordIssues enabledForFailure: true, tool: spotBugs()
            recordIssues enabledForFailure: true, tool: cpd(pattern: '**/target/cpd.xml')
            recordIssues enabledForFailure: true, tool: pmdParser(pattern: '**/target/pmd.xml')
        }
    }
}
